app = '[keycloak-rrmebq]'
primary_region = 'mia'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[[vm]]
  size = 'shared-cpu-2x'
  memory = '1gb'

[experimental]
  auto_rollback = true

[env]
  JAVA_OPTS_KC_HEAP = '-XX:MaxHeapFreeRatio=30 -XX:MaxRAMPercentage=65'
  KC_DB = 'postgres'
  KC_DB_PASSWORD = 'NgE3OcieFnR4'
  KC_DB_URL = 'postgresql://ronald:NgE3OcieFnR4@ep-red-boat-a57lmtp7.us-east-2.aws.neon.tech/keycloak?sslmode=require'
  KC_DB_USERNAME = 'ronald'
  KEYCLOAK_ADMIN = 'admin'
  KEYCLOAK_ADMIN_PASSWORD = '********'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[metrics]]
  port = 8080
  path = '/metrics'